import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@shopify/polaris/build/esm/styles.css";
import "./globals.css";
import { TopNavBar } from "@/components/client/top-navbar";
import { ReactQueryProvider } from "@/components/providers/react-query-provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-screen! flex flex-col">
        <ReactQueryProvider>
          <main className="flex-1!">
            <TopNavBar />
            {children}
          </main>
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
