import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "@shopify/polaris/build/esm/styles.css";
import "./globals.css";
import { TopNavBar } from "@/components/client/top-navbar";
import { ReactQueryProvider } from "@/components/providers/react-query-provider";
import { Toaster } from "@/components/ui/sonner";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${oswald.variable} h-full antialiased`}>
      <body className="min-h-screen! flex flex-col bg-[#F2F5FA]!">
        <ReactQueryProvider>
          <main className="flex-1!">
            <TopNavBar />
            {children}
          </main>
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
